In [2]:
import numpy as np

## array의  생성 

In [17]:
#np.array needs type assignment in contrast to conventional python dynamic type
test_array = np.array([1,2,3,4,5], np.float32)
test_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [20]:
test_array.dtype

dtype('float32')

In [22]:
test_array.shape

(5,)

In [23]:
test_array.ndim

1

In [24]:
test_array.size

5

In [25]:
test_matrix = np.array([[1,2,3],[4,5,6]],np.float32)

In [28]:
test_matrix.shape

(2, 3)

In [27]:
test_matrix.ndim

2

In [36]:
test_matrix.reshape(-1,)

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [38]:
test_matrix.reshape(-1,3)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [58]:
test_matrix[,1:]

array([], shape=(0, 2), dtype=float32)

In [59]:
np.identity(3, np.float32)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [61]:
test_diag = np.eye(3,4,2)

In [63]:
np.diag(test_diag, k=2)

array([1., 1.])

In [97]:
test_array1 = np.array([1,2,3],np.float32).reshape(-1,3)
test_array2 = np.array([4,5,6],np.float32).reshape(-1,3)

In [98]:
test_array1

array([[1., 2., 3.]], dtype=float32)

In [99]:
np.concatenate((test_array1,test_array2), axis =0)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [104]:
test_array1 = np.arange(1,7,1,dtype=np.float32).reshape(2,3)
test_array2 = np.arange(1,7,1,dtype=np.float32).reshape(3,2)

In [105]:
test_array1.dot(test_array2)

array([[22., 28.],
       [49., 64.]], dtype=float32)

In [109]:
#broadcasting
test_array = np.arange(1,5,1,dtype=np.float32).reshape(2,2)
scalar = 3
test_array + scalar

array([[4., 5.],
       [6., 7.]], dtype=float32)

In [110]:
# numpy for calculations but not for joining(concatenation)

In [118]:
#np.where
np.where(test_array > 1, 2,0)

array([[0, 2],
       [2, 2]])

In [119]:
A = np.arange(1,10).reshape(-1,3)

In [121]:
B = A % 2 == 0

In [122]:
B

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [123]:
B.astype(int)

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [127]:
#fancy index
b = [1,2,2,2,2,5]
print(A)
A.take(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 3, 3, 3, 3, 6])