In [1]:
import numpy as np
import torch

In [2]:
t = torch.FloatTensor([1,2,3])
print(t)

tensor([1., 2., 3.])


In [7]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0])

1
torch.Size([3])
torch.Size([3])
tensor(1.)


In [20]:
t = np.array( [ 
                  [ [0,1,2],
                    [3,4,5] ],
             
                  [ [6,7,8],
                    [9,10,11] ] 
              ])
t

ft = torch.FloatTensor(t)
ft


tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [27]:
print(ft.view([3,1,-1]))

tensor([[[ 0.,  1.,  2.,  3.]],

        [[ 4.,  5.,  6.,  7.]],

        [[ 8.,  9., 10., 11.]]])


In [21]:
print(ft.squeeze().shape)

torch.Size([2, 2, 3])


In [33]:
ft.squeeze(1)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [38]:
ft.unsqueeze(0).dim()

4

### linear regresssion 

In [55]:
hours = [1,2,3]
points = [2,4,6]

In [56]:
x_train = torch.FloatTensor(hours)
y_train = torch.FloatTensor(points)

In [57]:
w = torch.zeros(1, requires_grad = True)
# b = torch.zeros(1, requires_grad = True)

hypothesis = x_train * w # +b

In [52]:
# compute loss
#MSE
cost = torch.mean((hypothesis - y_train) ** 2)

In [59]:
optimizer = torch.optim.SGD([w], lr =0.01)

nb_epochs = 50

for epoch in range(1, nb_epochs + 1 ) :
    #H(X) 
    hypothesis = x_train * w # + b 
    
    #cost
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    print('Epoch {:4d}/{} W : {:.3f} Cost : {:.6f}'.format( epoch, nb_epochs, w.item(), cost.item()))
    
    
    #cost로 H(X) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

Epoch    1/50 W : 1.249 Cost : 2.630388
Epoch    2/50 W : 1.319 Cost : 2.162295
Epoch    3/50 W : 1.383 Cost : 1.777503
Epoch    4/50 W : 1.440 Cost : 1.461186
Epoch    5/50 W : 1.493 Cost : 1.201160
Epoch    6/50 W : 1.540 Cost : 0.987407
Epoch    7/50 W : 1.583 Cost : 0.811692
Epoch    8/50 W : 1.622 Cost : 0.667247
Epoch    9/50 W : 1.657 Cost : 0.548507
Epoch   10/50 W : 1.689 Cost : 0.450897
Epoch   11/50 W : 1.718 Cost : 0.370657
Epoch   12/50 W : 1.744 Cost : 0.304697
Epoch   13/50 W : 1.768 Cost : 0.250474
Epoch   14/50 W : 1.790 Cost : 0.205901
Epoch   15/50 W : 1.810 Cost : 0.169260
Epoch   16/50 W : 1.827 Cost : 0.139139
Epoch   17/50 W : 1.843 Cost : 0.114378
Epoch   18/50 W : 1.858 Cost : 0.094024
Epoch   19/50 W : 1.871 Cost : 0.077292
Epoch   20/50 W : 1.883 Cost : 0.063538
Epoch   21/50 W : 1.894 Cost : 0.052231
Epoch   22/50 W : 1.904 Cost : 0.042936
Epoch   23/50 W : 1.913 Cost : 0.035295
Epoch   24/50 W : 1.921 Cost : 0.029014
Epoch   25/50 W : 1.929 Cost : 0.023851


tensor(0.0006, grad_fn=<MeanBackward0>)
